# markdownlint configuration
default: true

# MD013 - Line length
MD013:
  line_length: 120
  code_blocks: false
  tables: false

# MD033 - Inline HTML
MD033: false

# MD041 - First line heading
MD041: false
