trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - infastructure/*

variables:
  buildConfiguration: "Release"

jobs:
  - job: Windows

    pool:
      vmImage: "windows-2019"
    variables:
      - group: "Git Hub"

    steps:
      - task: DotNetCoreInstaller@0
        inputs:
          version: "5.0.100"

      - task: Cake@0
        inputs:
          script: "build.cake"
          target: "CI-Build"
          verbosity: "Verbose"
        env:
          COREHOST_TRACE: 0
          DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
          DOTNET_CLI_TELEMETRY_OPTOUT: 1

      - task: PublishTestResults@2
        inputs:
          testRunner: VSTest
          testResultsFiles: '.test-results\*.trx'

      - task: PublishCodeCoverageResults@1
        inputs:
          codeCoverageTool: "Cobertura"
          summaryFileLocation: "cobertura-coverage.xml"

      - task: CopyFiles@2
        inputs:
          contents: 'publish\webapplication.zip'
          targetFolder: $(Build.ArtifactStagingDirectory)

      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: $(Build.ArtifactStagingDirectory)
          artifactName: WebApplicationBundle

      - task: GitHubPagesPublish@1
        inputs:
          docPath: 'docFx\_site\*'
          githubusername: $(git_username)
          githubemail: $(git_email)
          githubaccesstoken: $(Nukeeper_github_token)
          repositoryname: "AzureDevOpsKats"
          branchname: "gh-pages"
          commitmessage: "Automated Release"
