export const GET_ERRORS = 'GET_ERRORS';
export const RECEIVED_CATS_LIST = 'RECEIVED_CATS_LIST';
export const RECEIVED_CAT_DATA = 'RECEIVED_CAT_DATA';
export const REFRESH_LIST = 'REFRESH_LIST';
export const ADDED_ITEM = 'ADDED_ITEM';
export const UPDATED_ITEM = 'UPDATED_ITEM';
export const DELETED_ITEM = 'DELETED_ITEM';