version: "3.3"

services:

  traefik:
    image: traefik:v2.4
    container_name: "traefik"
    ports:
      - "80:80"
      - "443:443"
      - "5000:5000"
      - "8080:8080"
    labels:
      - traefik.enable=true
      - traefik.docker.network=webgateway
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/certs:/etc/traefik/certs"
      - "./traefik/traefik.toml:/etc/traefik/traefik.toml"
      - "./traefik/dyn.toml:/etc/traefik/dyn.toml"
    networks:
      - webgateway

  core-app:
    hostname: azuredevopskats-web
    image: "stuartshay/azuredevopskats:latest"
    expose: [ 5000 ]
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    labels:
      - traefik.enable=true
      - traefik.http.routers.api-service.rule=Host(`api.service.localhost`)
      - traefik.port=5000
    networks:
      - webgateway

networks:
  webgateway:
    driver: bridge
