version: '3.8'

services:

  azuredevopskats-web:
    hostname: azuredevopskats-web
    build:
      context: ..
      dockerfile: docker/azuredevopskats-web-multi.dockerfile/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
