version: '3.8'

services:

  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - azuredevopskats-network
      - elastic

  azuredevopskats-web:
    hostname: azuredevopskats-web
    image: "stuartshay/azuredevopskats:5.1-buildx-01"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    labels:
      - traefik.enable=true
      - traefik.http.routers.azuredevopskats-web.rule=Host(`azuredevopskats-web`)
      - traefik.http.routers.azuredevopskats-web.entrypoints=web
      - traefik.port=5000
    depends_on:
      - redis
    ports:
      - "5000:5000"
    networks:
      - azuredevopskats-network
      - elastic

  redis:
    image: bitnami/redis
    container_name: redis
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis-data:/data
    networks:
      - azuredevopskats-network
      - elastic

volumes:
  redis-data:

    null
networks:
  azuredevopskats-network: null
  elastic:
    driver: bridge
