plugin: aws_ec2
regions:
  - us-east-1
aws_profile: awsdevopskats
filters:
  instance-state-name : running
  tag:application: devopskats
  tag:env: shared
  tag:owner: devops
  tag:Name: devopskats-jumpbox
compose:
  ansible_host: public_ip_address
