name: Config Jumpbox

env:
  ANSIBLE_CHDIR: terraform/ansible/jumpbox
  AWS_REGION: us-east-1
  AWS_PROFILE_NAME: awsdevopskats

on:
  workflow_dispatch:
    inputs:
      ansible_action:
        type: choice
        description: Ansible Action
        required: true
        default: check_diff
        options:
          - apply
          - check_diff

jobs:
  config:
    runs-on: ubuntu-latest
    steps:
      - name: Add profile credentials to ~/.aws/credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile ${{ env.AWS_PROFILE_NAME }}
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile ${{ env.AWS_PROFILE_NAME }}

      - name: Setup python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3

      - name: Install python boto3, ansible
        run: |
          pip install boto3 requests ansible==2.9.6 ansible-lint==4.2.0

      - name: set ansible config secrets
        env:
          SSH_KEY: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}
        run: |
          mkdir -pv ${{ env.ANSIBLE_CHDIR }}/.ssh
          echo "$SSH_KEY" >  ${{ env.ANSIBLE_CHDIR }}/.ssh/id_rsa
          chmod 600  ${{ env.ANSIBLE_CHDIR }}/.ssh/id_rsa

      - name: Lint Ansible Playbook
        run: |
          pwd
          ansible-lint -x 403 ${{ env.ANSIBLE_CHDIR }}/tasks.yml

      - name: Run ansible playbook check diff
        if: github.event.inputs.ansible_action == 'check_diff'
        run: |
          pwd
          ansible-playbook ${{ env.ANSIBLE_CHDIR }}/tasks.yml -u ${{ secrets.ANSIBLE_SSH_USER }} -i ${{ env.ANSIBLE_CHDIR }}/inventory_aws_ec2.yml --private-key ${{ env.ANSIBLE_CHDIR }}/.ssh/id_rsa --check --diff -vv

      - name: Run ansible playbook apply
        if: github.event.inputs.ansible_action == 'apply'
        run: |
          pwd
          ansible-playbook ${{ env.ANSIBLE_CHDIR }}/tasks.yml -u ${{ secrets.ANSIBLE_SSH_USER }} -i ${{ env.ANSIBLE_CHDIR }}/inventory_aws_ec2.yml --private-key ${{ env.ANSIBLE_CHDIR }}/.ssh/id_rsa -vv
