name: Config Jumpbox

env:
  ANSIBLE_CHDIR: terraform/ansible/jumpbox
  AWS_REGION: us-east-1
  AWS_PROFILE_NAME: awsdevopskats

on:
  workflow_dispatch:
    inputs:
      ansible_action:
        type: choice
        description: Ansible Action
        required: true
        default: check_diff
        options:
          - apply
          - check_diff

jobs:
  config:
    uses: stuartshay/WorkflowCommon/.github/workflows/config-jumpbox.yml@master
    with:
      ANSIBLE_ACTION: ${{ github.event.inputs.ansible_action }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ANSIBLE_SSH_PRIVATE_KEY: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}
      ANSIBLE_SSH_USER: ${{ secrets.ANSIBLE_SSH_USER }}