name: Deploy ECS
env:
  AWS_ECR_REPOSITORY: azuredevopskats
  AWS_REGION: us-east-1
  DOCKER_FILE: docker/azuredevopskats-web-multi.dockerfile/Dockerfile
  AWS_ECR_DOCKER_IMAGE_TAG: 5.1-${{ github.run_number }}-buildx-${{ github.sha }}
  BRANCH_NAME: "${{ github.ref_name }}"
  ECS_SERVICE: "${{ github.ref_name }}-devops"
  ECS_CLUSTER: "${{ github.ref_name }}-devops"
  S3_STATE_BUCKET_NAME: "devops-team-tfstate"
  BUILD_NUMBER: ${{ github.run_number }}
  MASTER_ECS_DESIRED_COUNT: 2

on:
  workflow_dispatch:
    inputs:
      desired_count:
        type: choice
        description: ECS Desired Count
        required: true
        options:
          - 0
          - 1
          - 2
          - 5

  push:
    paths:
      - "src/**"
      - "test/**"
    branches:
      - master
      - develop
      - "feature/**"
      - "fix/**"

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_DEPLOY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_DEPLOY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

  build:
    needs: test-coverage
    runs-on: ubuntu-latest
    outputs:
      dotnet: ${{ steps.dotnet-version.outputs.dotnet }}
    strategy:
      matrix:
        dotnet: ["5.0.x"]

    steps:
      - id: dotnet-version
        run: echo "::set-output name=dotnet::${{ matrix.dotnet }}"

      - uses: actions/checkout@v2

      - name: Setup dotnet ${{ matrix.dotnet }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Install dependencies
        run: dotnet restore

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Available Buildx platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_DEPLOY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_DEPLOY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.AWS_ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker buildx create --name mybuilder --use
          docker buildx build -f ${{ env.DOCKER_FILE }} --platform linux/amd64 --load  \
               --build-arg BUILD_NUMBER=${{ env.BUILD_NUMBER }} -t $ECR_REGISTRY/$ECR_REPOSITORY:$AWS_ECR_DOCKER_IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$AWS_ECR_DOCKER_IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$AWS_ECR_DOCKER_IMAGE_TAG"
  deploy:
    needs: build
    runs-on: ubuntu-latest
    outputs:
      app_url: ${{ steps.set_app_url.outputs.app_url }}
    steps:
      - name: Configure AWS credentials
        id: aws-cred
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_DEPLOY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_DEPLOY }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: actions/checkout@v2

      - uses: kayac/ecspresso@v1
        with:
          version: v1.7.5

      - name: ECS deploy
        env:
          AWS_ACCOUNT_ID: ${{ steps.aws-cred.outputs.aws-account-id }}
        run: |
          #ECS_DESIRED_COUNT=1
          #if [ "$BRANCH_NAME" == "master" ]
          #then
          #  ECS_DESIRED_COUNT=$MASTER_ECS_DESIRED_COUNT
          #fi
          ECS_DESIRED_COUNT=${{ github.event.inputs.desired_count }}
          echo "::set-output AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID"
          cd ecspresso
          ecspresso --ext-str branch_name=$BRANCH_NAME --ext-code desired_count=$ECS_DESIRED_COUNT verify
          SERVICE_STATUS=$(aws ecs describe-services --cluster $ECS_CLUSTER --services $ECS_SERVICE | jq --raw-output 'select(.services[].status != null ) | .services[].status')
          echo $SERVICE_STATUS
          if [ -z "$SERVICE_STATUS" ] || [ "$SERVICE_STATUS" == "INACTIVE" ]
          then
            ecspresso --ext-str branch_name=$BRANCH_NAME --ext-code desired_count=$ECS_DESIRED_COUNT create
          else
            ecspresso --ext-str branch_name=$BRANCH_NAME --ext-code desired_count=$ECS_DESIRED_COUNT diff
            ecspresso --ext-str branch_name=$BRANCH_NAME --ext-code desired_count=$ECS_DESIRED_COUNT deploy
          fi
      - name: Set Task Public IP
        run: |
          TASK_ARN=$(aws ecs list-tasks --cluster $ECS_CLUSTER --service-name $ECS_SERVICE --query 'taskArns[0]' --output text)
          TASK_DETAILS=$(aws ecs describe-tasks --cluster $ECS_CLUSTER --task "${TASK_ARN}" --query 'tasks[0].attachments[0].details')
          ENI=$(echo $TASK_DETAILS | jq -r '.[] | select(.name=="networkInterfaceId").value')
          PUBLIC_IP=$(aws ec2 describe-network-interfaces --network-interface-ids "${ENI}" --query 'NetworkInterfaces[0].Association.PublicIp' --output text)
          echo "TASK_PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV
      - name: Get Task Public IP
        id: set_app_url
        run: |
          echo "ECS Task Public IP: ${{ env.TASK_PUBLIC_IP }}"
          if [ "$BRANCH_NAME" != "master" ]
          then
            echo "::set-output name=app_url::${{ env.TASK_PUBLIC_IP }}:5000"
          else
            APP_URL=$(aws elbv2 describe-load-balancers --names $ECS_CLUSTER --query 'LoadBalancers[0].DNSName' --output text)
            echo "::set-output name=app_url::$APP_URL"
          fi

  health-check:
    needs: deploy
    runs-on: ubuntu-latest
    env:
      url: ${{needs.deploy.outputs.app_url}}/health
      max-attempts: 15
      retry-delay-sec: 5
    steps:
      - name: Application health check
        run: |
          echo "ECS Task Public IP: ${{needs.deploy.outputs.app_url}}"
          curl --fail -s --retry ${{ env.max-attempts }} --retry-delay ${{ env.retry-delay-sec }} --retry-connrefused ${{ env.url }} -L  | jq
