name: Deploy Azure Linux Container
env:
  AZURE_REPOSITORY: azuredevopskats.web
  AZURE_DOCKER_IMAGE_TAG: 6.0.${{ github.run_number }}-buildx-${{ github.sha }}
  AZURE_DOCKER_IMAGE: ${{ secrets.REGISTRY_LOGIN_SERVER }}/azuredevopskats.web:6.0.${{ github.run_number }}-buildx-${{ github.sha }}
  BUILD_NUMBER: ${{ github.run_number }}
  DOCKER_FILE: docker/azuredevopskats-web-multi.dockerfile/Dockerfile
  BRANCH_NAME: "${{ github.ref_name }}"
  DEFAULT_ECS_DESIRED_COUNT: 1

on:
  workflow_dispatch:
    inputs:
      desired_count:
        type: choice
        description: Container Desired Count
        required: true
        default: 1
        options:
          - 0
          - 1
          - 2
          - 5

  push:
    paths:
      - "src/**"
      - "test/**"
    branches:
      - master
      - develop

jobs:
  docker-build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v2

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%SZ')"

      - name: Docker Image Uri
        run: echo $AZURE_DOCKER_IMAGE

      = name: Azure Container Registry Login
      - uses: azure/docker-login@v1
        with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}





      - name: "Build and push image"
        id: build-image
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build -f ${{ env.DOCKER_FILE }} \
                --build-arg BUILD_DATE=${{ steps.date.outputs.date }} \
                --build-arg BUILD_NUMBER=${{ env.BUILD_NUMBER }} \
                -t ${{ env.AZURE_DOCKER_IMAGE }} .
          docker push ${{ env.AZURE_DOCKER_IMAGE }}

      - name: "Deploy to Azure Container Instances"
        uses: "azure/aci-deploy@v1"
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          location: "eastus"
          dns-name-label: azuredevopskats999323
          image: ${{ env.AZURE_DOCKER_IMAGE }}
          #image: stuartshay/azuredevopskats
          name: azuredevopskats-container
          azure-file-volume-share-name: "devopskatsimages"
          azure-file-volume-account-name: "azurekatsimages01"
          azure-file-volume-account-key: ${{ secrets.AZURE_FILE_VOLUME_KEY }}
          azure-file-volume-mount-path: /images
          environment-variables: ASPNETCORE_ENVIRONMENT=AzureContainer
          log-analytics-workspace: ${{ secrets.LOG_ANALYTICS_WORKSPACE }}
          log-analytics-workspace-key: ${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}
          log-type: "ContainerInstanceLogs"
          registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          ports: 5000
