name: Deploy ECS Service Tasks
env:
  AWS_ECR_REPOSITORY: azuredevopskats
  AWS_REGION: us-east-1
  DOCKER_FILE: docker/azuredevopskats-web-multi.dockerfile/Dockerfile
  #AWS_ECR_DOCKER_IMAGE_TAG: 6.0.${{ github.run_number }}-buildx-${{ github.sha }}
  AWS_ECR_DOCKER_IMAGE_TAG: 6.0.81-buildx-cb8eedd7441212ea6f45c50b3e7cec43330ff746
  BRANCH_NAME: "${{ github.ref_name }}"
  ECS_SERVICE: "devopskats-${{ github.ref_name }}"
  ECS_CLUSTER: "devopskats-${{ github.ref_name }}"
  S3_STATE_BUCKET_NAME: "devops-team-tfstate"
  BUILD_NUMBER: ${{ github.run_number }}
  DEFAULT_ECS_DESIRED_COUNT: 1

on:
  workflow_dispatch:
    inputs:
      desired_count:
        type: choice
        description: ECS Desired Count
        required: true
        default: 1
        options:
          - 0
          - 1
          - 2
          - 5

  push:
    paths:
      - "src/**"
      - "test/**"
    branches:
      - master

jobs:
  # test-coverage:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Configure AWS credentials
  #       uses: aws-actions/configure-aws-credentials@v1
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: ${{ env.AWS_REGION }}

  #     - name: Login to Amazon ECR
  #       id: login-ecr
  #       uses: aws-actions/amazon-ecr-login@v1

  # build:
  #   needs: test-coverage
  #   runs-on: ubuntu-latest
  #   outputs:
  #     dotnet: ${{ steps.dotnet-version.outputs.dotnet }}
  #   strategy:
  #     matrix:
  #       dotnet: ["6.0.x"]

  #   steps:
  #     - id: dotnet-version
  #       run: echo "::set-output name=dotnet::${{ matrix.dotnet }}"

  #     - uses: actions/checkout@v2

  #     - name: Setup dotnet ${{ matrix.dotnet }}
  #       uses: actions/setup-dotnet@v1
  #       with:
  #         dotnet-version: ${{ matrix.dotnet }}

  #     - name: Install dependencies
  #       run: dotnet restore

  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v1

  #     - name: Set up Docker Buildx
  #       id: buildx
  #       uses: docker/setup-buildx-action@v1

  #     - name: Available Buildx platforms
  #       run: echo ${{ steps.buildx.outputs.platforms }}

  #     - name: Configure AWS credentials
  #       uses: aws-actions/configure-aws-credentials@v1
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: ${{ env.AWS_REGION }}

  #     - name: Login to Amazon ECR
  #       id: login-ecr
  #       uses: aws-actions/amazon-ecr-login@v1

  #     - name: Get current date
  #       id: date
  #       run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%SZ')"

  #     - name: Build, tag, and push image to Amazon ECR
  #       id: build-image
  #       env:
  #         ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
  #         ECR_REPOSITORY: ${{ env.AWS_ECR_REPOSITORY }}
  #         IMAGE_TAG: ${{ github.sha }}
  #       run: |
  #         docker buildx create --name mybuilder --use
  #         docker buildx build -f ${{ env.DOCKER_FILE }} --platform linux/amd64 --load  \
  #              --build-arg BUILD_DATE=${{ steps.date.outputs.date }} \
  #              --build-arg BUILD_NUMBER=${{ env.BUILD_NUMBER }} -t $ECR_REGISTRY/$ECR_REPOSITORY:$AWS_ECR_DOCKER_IMAGE_TAG .
  #         docker push $ECR_REGISTRY/$ECR_REPOSITORY:$AWS_ECR_DOCKER_IMAGE_TAG
  #         echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$AWS_ECR_DOCKER_IMAGE_TAG"
  
  deploy:
    #needs: build
    runs-on: ubuntu-latest
    outputs:
      app_url: ${{ steps.set_app_url.outputs.app_url }}
      ecs_desired_count: ${{ steps.ecs_deploy.outputs.ecs_desired_count }}
    steps:
      - name: Configure AWS credentials
        id: aws-cred
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: actions/checkout@v2

      - uses: kayac/ecspresso@v1
        with:
          version: v1.7.5

      - name: Set ECS cluster and service
        run: |
          if [ "$BRANCH_NAME" != "master" ]
          then
              echo "Set new ECS cluster and service to develop..."
              echo "ECS_CLUSTER=devopskats-develop" >> $GITHUB_ENV
              echo "ECS_SERVICE=devopskats-develop" >> $GITHUB_ENV
              echo "BRANCH_NAME=develop" >> $GITHUB_ENV
          fi
      - name: ECS deploy
        id: ecs_deploy
        env:
          AWS_ACCOUNT_ID: ${{ steps.aws-cred.outputs.aws-account-id }}
        run: |
          ECS_DESIRED_COUNT=${{ github.event.inputs.desired_count }}
          if [ -z "$ECS_DESIRED_COUNT" ]
          then
              ECS_DESIRED_COUNT=${{ env.DEFAULT_ECS_DESIRED_COUNT }}
          fi
          echo "::set-output name=ecs_desired_count::$ECS_DESIRED_COUNT"
          echo "ECS_DESIRED_COUNT=$ECS_DESIRED_COUNT" >> $GITHUB_ENV
          cd ecspresso
          ecspresso --ext-str branch_name=$BRANCH_NAME --ext-code desired_count=$ECS_DESIRED_COUNT verify
          SERVICE_STATUS=$(aws ecs describe-services --cluster $ECS_CLUSTER --services $ECS_SERVICE | jq --raw-output 'select(.services[].status != null ) | .services[].status')
          echo $SERVICE_STATUS
          if [ -z "$SERVICE_STATUS" ] || [ "$SERVICE_STATUS" == "INACTIVE" ]
          then
            ecspresso --ext-str branch_name=$BRANCH_NAME --ext-code desired_count=$ECS_DESIRED_COUNT create
          else
            ecspresso --ext-str branch_name=$BRANCH_NAME --ext-code desired_count=$ECS_DESIRED_COUNT diff
            ecspresso --ext-str branch_name=$BRANCH_NAME --ext-code desired_count=$ECS_DESIRED_COUNT deploy
          fi
      # - name: Set Task Public IP
      #   if: ${{ env.ECS_DESIRED_COUNT > 0 }}
      #   run: |
      #     TASK_ARN=$(aws ecs list-tasks --cluster $ECS_CLUSTER --service-name $ECS_SERVICE --query 'taskArns[0]' --output text)
      #     TASK_DETAILS=$(aws ecs describe-tasks --cluster $ECS_CLUSTER --task "${TASK_ARN}" --query 'tasks[0].attachments[0].details')
      #     ENI=$(echo $TASK_DETAILS | jq -r '.[] | select(.name=="networkInterfaceId").value')
      #     PUBLIC_IP=$(aws ec2 describe-network-interfaces --network-interface-ids "${ENI}" --query 'NetworkInterfaces[0].Association.PublicIp' --output text)
      #     echo "TASK_PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV
      # - name: Get Task Public IP
      #   if: ${{ env.ECS_DESIRED_COUNT > 0 }}
      #   id: set_app_url
      #   run: |
      #     echo "ECS Task Public IP: ${{ env.TASK_PUBLIC_IP }}"
      #     if [ "$BRANCH_NAME" != "master" ]
      #     then
      #       echo "::set-output name=app_url::${{ env.TASK_PUBLIC_IP }}:5000"
      #     else
      #       APP_URL=$(aws elbv2 describe-load-balancers --names $ECS_CLUSTER --query 'LoadBalancers[0].DNSName' --output text)
      #       echo "::set-output name=app_url::$APP_URL"
      #     fi
      - name: Get Task Public IP
        if: ${{ env.ECS_DESIRED_COUNT > 0 }}
        id: set_app_url
        uses: stuartshay/WorkflowCommon/.github/workflows/get-ecs-app-url.yml@master
        with:
          ecs_cluster: $ECS_CLUSTER
          ecs_service: $ECS_SERVICE

  health-check:
    needs: deploy
    if: needs.deploy.outputs.ecs_desired_count > 0
    uses: stuartshay/WorkflowCommon/.github/workflows/health-check.yml@master
    with:
      test_url: ${{needs.deploy.outputs.app_url}}/health

  selenium-test:
    needs: [health-check, deploy]
    uses: stuartshay/WorkflowCommon/.github/workflows/selenium-test.yml@master
    with:
      test_url: "http://${{needs.deploy.outputs.app_url}}"
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_password: ${{ secrets.DOCKERHUB_TOKEN_AZUREKATS }}
