name: "Infrastructure - Deploy ALB"

env:
  BRANCH_NAME: ${{ github.ref_name }}
  TERRAFORM_CHDIR: terraform/XXXXXXXXX/${{ github.ref_name }}
  AWS_DEFAULT_REGION: us-east-1
  AWS_PROFILE_NAME: awsdevopskats

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        required: false
        default: master
        options:
          - master
      terraform_action:
        type: choice
        description: Terraform Action
        required: true
        default: plan
        options:
          - apply
          - plan
          - destroy

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          architecture: "x64"
