on:
  workflow_call:
    inputs:
      ecs_cluster:
        required: true
        type: string
      ecs_service:
        required: true
        type: string
    outputs:
      app_url:
        description: "The ECS application URL"
        value: ${{ jobs.get_app_url.outputs.app_url }}

jobs:
  get_app_url:
    runs-on: ubuntu-latest
    outputs:
      app_url: ${{ steps.set_app_url.outputs.app_url }}
    env:
      ecs_cluster: ${{ inputs.ecs_cluster }}
      ecs_service: ${{ inputs.ecs_service }}
    steps:
      - name: Set Task Public IP
        run: |
          TASK_ARN=$(aws ecs list-tasks --cluster $ECS_CLUSTER --service-name $ECS_SERVICE --query 'taskArns[0]' --output text)
          TASK_DETAILS=$(aws ecs describe-tasks --cluster $ECS_CLUSTER --task "${TASK_ARN}" --query 'tasks[0].attachments[0].details')
          ENI=$(echo $TASK_DETAILS | jq -r '.[] | select(.name=="networkInterfaceId").value')
          PUBLIC_IP=$(aws ec2 describe-network-interfaces --network-interface-ids "${ENI}" --query 'NetworkInterfaces[0].Association.PublicIp' --output text)
          echo "TASK_PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV

      - name: Get Task Public IP
        id: set_app_url
        run: |
          echo "ECS Task Public IP: ${{ env.TASK_PUBLIC_IP }}"
          if [ "$BRANCH_NAME" != "master" ]
          then
            echo "::set-output name=app_url::${{ env.TASK_PUBLIC_IP }}:5000"
          else
            APP_URL=$(aws elbv2 describe-load-balancers --names $ECS_CLUSTER --query 'LoadBalancers[0].DNSName' --output text)
            echo "::set-output name=app_url::$APP_URL"
          fi